title: IPND Syllabus
author: Wang Qun Feng
email: qunfengw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Introduction to Programming Syllabus for those who want to learn how to code.
  You will learn HTML, CSS, JavaScript and Python in this course. What's most exciting
  is you can get some feedback about your projects from an expert.
  

# social links
twitter_username: qunfengwang
github_username:  wqfeng

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
