title: IPND Syllabus
author: Wang Qun Feng
email: qunfengw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a syllabus for those who want to learn programming. You will learn the basics
  of HTML, CSS, JavaScript and Python. The most exceting part is you can learn by doing
  and get some feedback about your projects from an expert.

# social links
twitter_username: @qunfengwang
github_username:  wqfeng

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
